### ISSUE TITLE
滚动的动画可以transform：translate(0,-100%),这时候.cube-scroll-list-wrapper的min-height=0px

### ISSUE THREAD

**Issue by zhengyn0001** [cube-ui/question-answer#107]
滚动的动画可以transform：translate(0,-100%),这时候.cube-scroll-list-wrapper的min-height=0px
![image](https://user-images.githubusercontent.com/51322469/68520587-bf5b2d00-02d3-11ea-9d7c-cbdd79f93903.png)

**Comment by dolymood** [comment]
没明白啥意思？

**Comment by zhengyn0001** [comment]
就是滚动的时候可以滚到给的高度之上发自我的华为手机-------- 原始邮件 --------发件人： doly mood <notifications@github.com>日期： 2019年11月11日周一 16:53收件人： cube-ui/question-answer <question-answer@noreply.github.com>抄送： zhengyn0001 <1046611633@qq.com>, Author <author@noreply.github.com>主    题： Re: [cube-ui/question-answer] 滚动的动画可以transform：translate(0,-100%),这时候.cube-scroll-list-wrapper的min-height=0px (#107)没明白啥意思？

**Comment by zhengyn0001** [comment]
就是我只给cube-scroll传来data,没有配置option，想的是这个可以上下滚动，可以他这个可以一直滚，没有那种超过底部多少就会回弹

**Comment by dolymood** [comment]
cube-scroll 强依赖外层高度有效，即 height 100% 起到作用的场景 目测因为这个

**Comment by zhengyn0001** [comment]
可是我用开发者工具查看元素的时候，cube-scroll高度确实是有的

**Comment by dolymood** [comment]
就一条 规则 cube-scroll 的样式 height 100% 生效

我们会探索更好一点的方式，但目前还只能依赖这个

**Comment by ly15128022104** [comment]
产生的列表不具有滚动功能，只有当删除其中一项时，才能上下拖拽
