### ISSUE TITLE
input点击清除按钮无效

### ISSUE THREAD

**Issue by MeetYouZi** [cube-ui/question-answer#108]
input点击清除按钮无效，官网也有同样的问题。点击清除按钮，input框无法清除

**Comment by dolymood** [comment]
清除是touchend做的，需要移动设备才可以的

**Comment by MeetYouZi** [comment]
是移动端

**Comment by dolymood** [comment]
按照issue规范在 didi/cube-ui 下提issue吧，这个问题我这边找的几个手机 官网demo是没问题的
