### ISSUE TITLE
列表生成上传组件，怎么给只当前的项注册addedHandler等事件？

### ISSUE THREAD

**Issue by haoyinag** [cube-ui/question-answer#11]
<div class="apply-case-item" v-for="(item,index) in ImgArr">
                <cube-upload class="img" ref="upload" v-model="files" :action="action" @files-added="addedHandler(index)" @file-error="errHandler(index)">
                    <img class="img-template" :src="item.src" alt="">
                    <cube-upload-file class="upload-file" v-for="(file, i) in files" :file="file" :key="i"></cube-upload-file>
                    <cube-upload-btn :multiple="false">
                    </cube-upload-btn>
                </cube-upload>
                <cube-button @click="flieUpload(index)" class="item-btn">更改</cube-button>
            </div>

像这种结构，不知道怎么去给每个项单独注册。

**Comment by dolymood** [comment]
这种在群里问吧

https://github.com/didi/cube-ui/blob/dev/assets/cube-qq-QR.jpg
