### ISSUE TITLE
生成的vendor.js文件很大，better-normal-scroll v1.12.6 build后800k

### ISSUE THREAD

**Issue by a74586** [cube-ui/question-answer#111]
在vendor.js中，better-normal-scroll v1.12.6就有800多k，导致vendor.js达到1M大小，看了官方示例生成的vendor.js中的better-normal-scroll才几十k，是什么原因导致的？

**Comment by dolymood** [comment]
不会，better-scroll 就几十K，不可能那么大，应该你的打包有问题
