### ISSUE TITLE
scrollNav 侧边式 右边滚动左边没有联级滚动

### ISSUE THREAD

**Issue by tongtong12** [cube-ui/question-answer#116]
按照官方文档 label 也都加上了 但是右边列表滚动时，左边的导航栏没有依据内容进行转换。
sticky-change 事件里打印的都是 ‘cube-scroll-nav-bar’，找了好久没找出原因。
所以问下大佬们有没有办法

**Comment by dolymood** [comment]
如果是异步数据 需要等数据获取后初始化组件
