### ISSUE TITLE
官方文档说vue-cli > 3 的项目可以使用 cube-ui，那么除了vue add cube-ui具体还需要什么配置？

### ISSUE THREAD

**Issue by fuyunjinglong** [cube-ui/question-answer#118]
官方文档说vue-cli > 3 的项目可以使用 cube-ui，那么除了vue add cube-ui外具体还需要什么配置吗？官方文档没有详细介绍这块，能说明下吗？

**Comment by fuyunjinglong** [comment]
按照这个vue add cube-ui安装方式，启动项目提示TypeError: Cannot read property 'stylus' of undefined，项目中已经安装了这个依赖，这是怎么回事？

**Comment by fuyunjinglong** [comment]
急急急

**Comment by fuyunjinglong** [comment]
配置了vue.config.js后，提示TypeError: Cannot read property 'forEach' of undefined
怎么越来越诡异了

**Comment by dolymood** [comment]
初始化项目后 vue add cueb-ui 就可以
不需要额外的其他配置
