### ISSUE TITLE
ScrollNav无法往下滚动，左侧可以点击，但是右侧区域也不会滚动到指定位置

### ISSUE THREAD

**Issue by QiDa-007** [cube-ui/question-answer#128]
根据教程，数据也是用的jiaoche教程中的示例（使用的vue-cli 4.3.1版本）

![image](https://user-images.githubusercontent.com/11505520/82279787-e18ae180-99bf-11ea-84ea-5abd1c547384.png)

**Comment by dolymood** [comment]
scroll-list-wrap 需要使得height 100% 生效才可以的
