### ISSUE TITLE
dialog组件按钮无法显示，怎么回事

### ISSUE THREAD

**Issue by wellsea** [cube-ui/question-answer#139]
this.$createDialog({
                type: 'confirm',
                icon: 'cubeic-important',
                title: '',
                content: '谎报警情将依法承担法律责任，确定要继续拨打么？',
                confirmBtn: {
                    text: '确定拨打',
                    active: true,
                    disabled: false,
                    href: 'javascript:;'
                },
                cancelBtn: {
                    text: '取消',
                    active: false,
                    disabled: false,
                    href: 'javascript:;'
                },
                onConfirm: () => {
                    window.location.href = "tel:110";
                    // this.$createToast({
                    //     type: 'warn',
                    //     time: 1000,
                    //     txt: '点击确认按钮'
                    // }).show();
                },
                onCancel: () => {
                    // this.$createToast({
                    //     type: 'warn',
                    //     time: 1000,
                    //     txt: '点击取消按钮'
                    // }).show();
                }
            }).show();
            
            
            
按照上面调用，titile和取消的按钮都不显示，怎么回事

**Comment by dolymood** [comment]
可以给个复现demo
看代码不应该出现这种情况
