### ISSUE TITLE
nuxt 项目中该如何配置?

### ISSUE THREAD

**Issue by clownxh** [cube-ui/question-answer#19]

**Comment by dolymood** [comment]
nuxt 项目中不支持后编译配置，或者在node环境下不支持后编译，在浏览器环境支持后编译，分开打包也行。

**Comment by Cataunt** [comment]
nuxt项目中可以使用自定义主题嘛

**Comment by Cataunt** [comment]
请问nuxt项目中支持使用自定义主题？该如何配置呢？
Duplicate of #

**Comment by Cataunt** [comment]
请问nuxt项目中支持使用自定义主题？该如何配置呢？

**Comment by dolymood** [comment]
See https://github.com/cube-ui/cube-nuxt-demo
