### ISSUE TITLE
初始化项目时,后编译 选择no 单位px部位转为vw, vh  

### ISSUE THREAD

**Issue by xSeek-Neo** [cube-ui/question-answer#20]
1.初始化项目时,后编译 选择no 单位px不会转为vw, vh  
2.怎么自定义主题
![Uploading image.png…]()

**Comment by dolymood** [comment]
参见 wiki https://github.com/cube-ui/cube-template/wiki

目前是后编译的情况下才能转，非后编译情况，理论上是可以实现的
