### ISSUE TITLE
怎样修改组件内部元素的样式呢？

### ISSUE THREAD

**Issue by afei1217** [cube-ui/question-answer#23]
eg： 
<cube-checkbox class="default-address" >aaa</cube-checkbox> 

.default-address .cube-checkbox-ui i {
  color: red;
}
这样不能生效  应该是组件内部使用了scoped  
但是 怎样才能修改生效呢

**Comment by dolymood** [comment]
这个看vue官方文档 关于 scoped 样式 覆盖问题。
