### ISSUE TITLE
安装cube-ui之后，项目运行报错

### ISSUE THREAD

**Issue by bala00** [cube-ui/question-answer#24]
vue-cli快速创建的项目，未加cube-ui之前npm run serve可以正常启动，采用vue add cube-ui添加后，项目启动报错，提示Uncaught SyntaxError: Unexpected token ...     index.js ，命令窗口中一堆的warning: "export 'Validator' was not found in 'cube-ui',所有组件找不到，怎么搞？

**Comment by dolymood** [comment]
这种建议入群讨论，贴上自己命令
