### ISSUE TITLE
使用vue add cube-ui成功后运行依然报错！

### ISSUE THREAD

**Issue by luddite1989** [cube-ui/question-answer#28]
我在使用cube-ui时，按照官方安装cube-ui，依然提示错误。
![image](https://user-images.githubusercontent.com/11624146/49197130-ab6f3180-f3c8-11e8-9d09-471e7738711f.png)
![image](https://user-images.githubusercontent.com/11624146/49197135-b88c2080-f3c8-11e8-90e9-9b54e8253547.png)
![image](https://user-images.githubusercontent.com/11624146/49197145-c346b580-f3c8-11e8-9702-6bab04985c55.png)

**Comment by luddite1989** [comment]
我只能说这个控件是我用过配置最复杂而且还容易出错的控件。

**Comment by dolymood** [comment]
vue-cli @3 的版本没有 run dev 啊就，而且你这项目明显不是用的 vue cli @3 的项目，但是你配置了 3 的用法

**Comment by luddite1989** [comment]
@dolymood 我想知道我这为什么不是vue-cli @3 ？我的版本是3.1.3，没有run dev，你用什么命令启动项目？

**Comment by dolymood** [comment]
用 vue-cli 3 的项目创建出来的是 npm run serve 吧 而且命令也不是直接调用的 webpack-dev-serve
