### ISSUE TITLE
upload组件 可以实现一个接口上传多张图片吗

### ISSUE THREAD

**Issue by somggud** [cube-ui/question-answer#36]
1.当上传多张图片时，我想等到所有图片都上传到 服务器完毕后（无论成功或者失败） 做一个逻辑判断，但是我找不到所有图片上传完成的钩子或者时机，有大神能指导一下吗
2.因后台上传有并发限制，如果需要一次接口上传多张图片，该怎么办呢

**Comment by dolymood** [comment]
1. 找不到所有图片上传完成的钩子，有单个的钩子，这个自己check就好了
2. 一次接口上传多张图片不现实
