### ISSUE TITLE
当不设置回弹停留位置时，下拉刷新总是会直接回弹

### ISSUE THREAD

**Issue by rickkky** [cube-ui/question-answer#41]
```
    pullDownRefresh: {
      threshold: 50,
      stop: 40,
      stopTime: 2000,
      txt: '加载成功',
    }
```

文档中说“”组件会自动计算回弹时显示的元素高度作为默认值“，但是我在实际使用的时候如果不设置 `stop` 属性，下拉以后（无论是否还在加载中）都会直接回弹，这是什么原因造成的？（ps. 使用的是内置的下拉刷新动画）
如果设置 `stop` 属性的话，由于使用了 `vw` 布局，屏幕较窄时可能会导致停留位置过高，屏幕较宽时会导致停留位置较低文字显示不完全。

**Comment by dolymood** [comment]
当不设置的时候 是会自动获取的。请按照issue规范提，谢谢。
