### ISSUE TITLE
使用Scroll的时候，用v-show显示隐藏后无法滚动

### ISSUE THREAD

**Issue by Max-Law** [cube-ui/question-answer#45]
![image](https://user-images.githubusercontent.com/24608133/54510459-4a279a00-4988-11e9-8544-22cfd58e7d4b.png)

当触发v-show后，scroll就无法滚动了，使用 this.$refs.scroll.refresh()；也没有反应

**Comment by tank0317** [comment]
问题解决了吗？
确定是一开始可以滚动，隐藏后再显示，无法滚动？

我这没有复现，能提供个链接看下吗？

不好意思，回复晚了

**Comment by Max-Law** [comment]
能告诉我this.$refs.scroll.refresh()；这样调用的方法是对的吗？
cube创造的better-scroll实例是this.$refs.scroll还是this.scroll？调用都没反应

**Comment by Max-Law** [comment]
没事了，我解决了~麻烦了

**Comment by liyan888** [comment]
可以问下是怎么解决的么？我也出现了这样的问题
