### ISSUE TITLE
 Native Scroll 没有效果

### ISSUE THREAD

**Issue by yezizi** [cube-ui/question-answer#47]
![image](https://user-images.githubusercontent.com/24238082/54741594-ec01ed80-4bf9-11e9-8ccd-e328a0cf46d3.png)

**Comment by yezizi** [comment]
组件已经全局

**Comment by yezizi** [comment]
这个组件需要引入better-scroll 组件吗

**Comment by tank0317** [comment]
问题解决了吗？你这个是嵌套的 scroll 吗？

**Comment by yezizi** [comment]
没解决，换 Scroll 了
