### ISSUE TITLE
使用 vue-cli-plugin-cube-ui  配置完询问项后报错，报错信息如下

### ISSUE THREAD

**Issue by GarrenZhang** [cube-ui/question-answer#48]
Error: EPERM: operation not permitted, open 'C:\Users\MSI\Desktop\portalwechat\.svn\pristine\00\003949e3afc3429299593f196b1d26f0b9c12f4d.svn-base'

**Comment by JnStyles** [comment]
没有权限的问题，mac的话， 执行 sudo chmod -R 777 path  window，用管理员打开
