### ISSUE TITLE
嵌套scrolll，内部没有出现滚动条，无法通过内部滑动触发外部滑动。

### ISSUE THREAD

**Issue by clydee-geng** [cube-ui/question-answer#50]
当使用nestMode="free"实现内部滚动条滑动到边界，从而触发外部滚动时。如果内部scroll的content高度不够没有出现滚动条，则无法通过内部滑动触发外部滑动。除了内部scroll设置min-height，还有更好的方法吗？

**Comment by tank0317** [comment]
是组件的一个问题，稍后会发一个修复版本。

**Comment by tank0317** [comment]
[v1.12.15](https://github.com/didi/cube-ui/releases/tag/v1.12.15) 已修复。可以更新到最新版试下。
