### ISSUE TITLE
嵌套scroll，内部scroll组件数据更新后，内部scroll高度没更新导致不能滑动

### ISSUE THREAD

**Issue by clydee-geng** [cube-ui/question-answer#51]
嵌套scroll，内部scroll组件数据请求完成后（没有图片，纯文字），内部scroll的高度没更新导致无法滑动。内部scroll使用的是默认options。即observeDOM: true似乎没有生效？目前是setTimeout里手动调用内部scroll的refush方法解决的。还有更好的方法吗？

**Comment by tank0317** [comment]
高度没有更新？我这是正常的，你能提供个demo例子看下吗？最好是一个链接
