### ISSUE TITLE
嵌套scroll，内部和外部都使用相同的自定义options,轻拂内部scroll，第一次不能滑动，第二次生效

### ISSUE THREAD

**Issue by clydee-geng** [cube-ui/question-answer#52]
嵌套scroll，内部和外部都使用相同的自定义options,
`scrollOptions: {
        observeDOM: true,
        click: true,
        probeType: 3,
        scrollbar: false,
        pullDownRefresh: false,
        pullUpLoad: false,
        // startY: -100,
        bounce: {
          //关闭回弹动画
          top: false,
          bottom: false,
          left: false,
          right: false
        },
        stopPropagation: true
      },`
用来取消两个scroll的橡皮筋效果。
轻拂内部scroll，第一次不滑动，第二次生效。
如果内部不加自定义的options，轻拂内部scroll，第一次就生效。

**Comment by tank0317** [comment]
没有复现，能提供个复现的链接吗
