### ISSUE TITLE
移动端网页长按不能保存图片的问题

### ISSUE THREAD

**Issue by LiuPure** [cube-ui/question-answer#53]
你好有碰到用了滚动组件后移动端网页长按不能保存图片的问题吗

**Comment by dolymood** [comment]
bs的配置项 preventDefault 需要置为 false 的情况下 才可以长按保存

**Comment by LiuPure** [comment]
能具体一点嘛感谢感谢，刚入门不久不太了解，bs的配置项需要在哪里更改呢？
