### ISSUE TITLE
上拉加载的是否可以在一开始的时候就设置成nomore？

### ISSUE THREAD

**Issue by AboyL** [cube-ui/question-answer#56]
第一次加载数据的时候因为数据不够一页，所以设置了
forceUpdate(false)
但是因为没有滚动的原因 所以往下面滚动的时候还是会先看到 加载更多这几个字
然后超过阈值以后才会切换成 nomore的文字

我现在希望第一次加载数据以后就能直接显示nomore文字，而不是滚动到底部再切换过去
应该怎么做？
还是说这个是一个bug？

**Comment by dolymood** [comment]
cube-ui 1.12.21 解决了这个问题，可以设置 `pullUpLoad.visible` 为 `true`，以及 实例方法 `forceUpdate` 增加了第二个参数 `nomore` 详见文档 https://didi.github.io/cube-ui/#/zh-CN/docs/scroll
