### ISSUE TITLE
form表单的配置能否动态化？

### ISSUE THREAD

**Issue by LiyinZhang** [cube-ui/question-answer#62]
form表单代码如下：
<template>
  <cube-form :model="model" @validate="validateHandler" @submit="submitHandler">
    <template v-for="item in datas">
      <cube-form-group v-for="group in item.groupList">
        <template v-for="iitem in group.fields">
          <cube-form-item :field="iitem" v-if="iitem.type !== 'dataselect'" v-bind:key="iitem.modelKey"></cube-form-item>
          <cube-form-item :field="iitem" v-else v-bind:key="iitem.modelKey">
            <cube-button @click="showDatePicker(iitem)">{{model[iitem.modelKey] || "Please select date" }}</cube-button>
            <date-picker ref="datePicker" :min="[2008, 8, 8]" :max="[2020, 10, 20]" @select="dateSelectHandler"></date-picker>
          </cube-form-item>
        </template>
      </cube-form-group>
      <cube-form-group v-if="item.multiterm">
        <cube-button type="button" @click="add(item)">添加</cube-button>
      </cube-form-group>
  </template>
    </cube-form>
</template>
<script>
import { DatePicker } from "cube-ui";
export default {
    props: {
      model: {
          type: Object,
          default(){
              return {}
          }
      },
      datas: {
          type: Array,
          default(){
              return []
          }
      }
    },
  data() {
    return {
      validity: {},
      valid: undefined
    };
  },
  components: {
    DatePicker
  },
    created(){
        console.log(this.model)
        debugger
    },
  methods: {
    submitHandler(e, model) {
        // alert('submit')
      e.preventDefault();
      this.$emit('submit', model)
      // console.log("submit", e);
      // console.log(this.model);
    },
    validateHandler(result) {
        // alert('validateHandler')
      this.validity = result.validity;
      this.valid = result.valid;
      console.log(
        "validity",
        result.validity,
        result.valid,
        result.dirty,
        result.firstInvalidFieldIndex
      );
    },
    resetHandler(e) {
      console.log("reset", e);
    },
    showDatePicker(iitem) {
        let item = {}
        item = iitem
        this.datePicker = ""
        if (!this.datePicker) {
            this.datePicker = this.$createDatePicker({
                title: 'Date Picker',
                min: [2008, 8, 8],
                max: [2020, 10, 20],
                value: this.model[item.modelKey] ? new Date(this.model[item.modelKey].replace(/-/g,"/")) : new Date(),
                format: {
                    year: 'YYYY年',
                    month: 'MM月',
                    date: ' DD日'
                },
                onSelect: (date, selectedVal, selectedText) => {
                    debugger
                    this.model[item.modelKey] = selectedVal && selectedVal.join("-");
                }
            })
        }

        this.datePicker.show()
    },
    dateSelectHandler(date, selectedVal, selectedText) {
        debugger
      this.model.dateValue = selectedVal && selectedVal.join("/");
    },
  // 数组添加函数
      add(item) {
        debugger
          let copyItem = Object.assign({}, item.groupList[0])
          item.groupList.push(copyItem)
      }
  }
};
</script>

model定义如下：
model： {
educationList: [
              {
                educationStartDate: "",
                educationEndDate: "",
                schoolName: "",
                major: "",
                degree: "",
                eduType: ""
              }
          ]
}
datas定义如下：
[
        {
          groupTitle: "教育信息",
          multiterm: true, // 是否多条数据
          groupList: [
            {
              groupType: "list",
              fields: [
                  {
                      type: "dataselect",
                      modelKey: "educationInfoDtos[0].educationStartDate",
                      label: "开始时间",
                      rules: {
                          required: true
                      }
                  },
                {
                  type: "input",
                  modelKey: "educationInfoDtos[0].schoolName",
                  label: "学校名称",
                  props: {
                    placeholder: "请输入"
                  },
                  rules: {
                    required: true
                  },
                  trigger: "blur"
                },
                  {
                      type: "select",
                      modelKey: "educationInfoDtos[0].eduType",
                      label: "学历",
                      props: {
                          options: ['本科', '大专']
                      }
                      // rules: {
                      //     required: true
                      // }
                  }
      ]
  }
]

界面效果如下：
![image](https://user-images.githubusercontent.com/35131595/57912975-303e0100-78be-11e9-8e12-266766303bf1.png)

当点击界面的添加按钮，会增加多一条教育信息，那么想问一下datas里面的modelKey应该怎么跟model建立关联，能做到这种需求吗？

**Comment by dolymood** [comment]
目测 使用 computed 可解决

**Comment by LiyinZhang** [comment]
你好，那我想问一下modelKey应该怎么写，可以举例一下？我现在是不知道model应该怎么跟modelkey关联起来。


------------------ 原始邮件 ------------------
发件人: "doly mood"<notifications@github.com>;
发送时间: 2019年5月17日(星期五) 下午5:04
收件人: "cube-ui/question-answer"<question-answer@noreply.github.com>;
抄送: "张力音"<963696044@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cube-ui/question-answer] form表单的配置能否动态化？ (#62)




目测 使用 computed 可解决

**Comment by dolymood** [comment]
model不支持复杂表达式，这个很容易有替代方案

**Comment by LiyinZhang** [comment]
就是想不出替代方案
项目卡在这里进行不下去了
方便说一下替代方案吗？


------------------ 原始邮件 ------------------
发件人: "doly mood"<notifications@github.com>;
发送时间: 2019年5月17日(星期五) 下午5:29
收件人: "cube-ui/question-answer"<question-answer@noreply.github.com>;
抄送: "张力音"<963696044@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [cube-ui/question-answer] form表单的配置能否动态化？ (#62)




model不支持复杂表达式，这个很容易有替代方案

**Comment by dolymood** [comment]
model 直接是对象，剩下的自己映射即可。
