### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by gh0sthx** [cube-ui/question-answer#67]
These relative modules were not found:

* ./cubeic.ttf in ./node_modules/css-loader??ref--11-1!./node_modules/postcss-loader/lib??ref--11-2!./node_modules/stylus-loader??ref--11-3!./node_modules/cube-ui/src/common/stylus/index.styl
* ./cubeic.woff in ./node_modules/css-loader??ref--11-1!./node_modules/postcss-loader/lib??ref--11-2!./node_modules/stylus-loader??ref--11-3!./node_modules/cube-ui/src/common/stylus/index.styl

**Comment by dolymood** [comment]
https://github.com/cube-ui/question-answer/issues/7
