### ISSUE TITLE
cube-tab-bar change icon

### ISSUE THREAD

**Issue by shiguangteng** [cube-ui/question-answer#71]
一般要是公司的项目开发,项这个tab-bar组件的图标怎么修改呢.难道都要用内置的的图标额........

**Comment by dolymood** [comment]
不会啊 直接就是icon，会加入到对应元素的class上，和内置图标没关系

**Comment by shiguangteng** [comment]
<div class="section">
        <cube-tab-bar
          v-model="selectedLabelDefault"
          :data="tabs"
          @click="clickHandler"
          @change="changeHandler">
        </cube-tab-bar>

tabs: [{
          label: 'Home',
          icon: 'cubeic-home'
        }, {
          label: 'Like',
          icon: 'cubeic-like'
        }, {
          label: 'Vip',
          icon: 'cubeic-vip'
        }, {
          label: 'Me',
          icon: 'cubeic-person'
        }]
我看例子是这样的.... tabs 这个数据集里面的 icon 值 是负责图标的显示,刚接触这个框架,您说的加入到对应元素的class 上是什么意思....抱歉水平比较菜 没明白

**Comment by shiguangteng** [comment]
我只关注第一个 default 的例子了 下面有  icon插槽的 是用这个来 实现自定义 图标对吧..
