### ISSUE TITLE
为什么<cube-recycle-list>需要注册

### ISSUE THREAD

**Issue by pretty8816** [cube-ui/question-answer#73]
请问为什么会报这个错？[Vue warn]: Unknown custom element: <cube-recycle-list> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
其实，我已经npm 安装了cube-ui，难道cube-recycle-list这个需要单独引用或注册吗？

**Comment by dolymood** [comment]
注意版本，且安装了还需要use的
