### ISSUE TITLE
add cube-ui export not found？不能按需引入只能引入全部

### ISSUE THREAD

**Issue by tang412** [cube-ui/question-answer#80]
vuecli3 add cube-ui 无法按需引入 只能引入全部

**Comment by dolymood** [comment]
还请提供更多细节

**Comment by tang412** [comment]
> 还请提供更多细节

vuecli3 按照官方文档 vue add cube-ui执行完成后 main.js  按需引入提示was not found 可以引入所有  还是搞不懂后编译有啥区别 后编译设置false 可以使用但组件样式出不来

**Comment by dolymood** [comment]
首先得确保自己本地项目也是用vue-cli3 生成的

我们内部所有项目都是这种方式，没有遇到问题

**Comment by tang412** [comment]
> 首先得确保自己本地项目也是用vue-cli3 生成的
> 
> 我们内部所有项目都是这种方式，没有遇到问题

当然是vuecli3  还是add cube-ui后的问题，cube感觉很不错但是用不好 现换用vant了，可能还是我太菜了
