### ISSUE TITLE
在scroll组件中，qcvideo组件播放了视频，点击视频区域无法调起暂停的操作面板，安卓中出现的

### ISSUE THREAD

**Issue by JElaine** [cube-ui/question-answer#90]
在scroll组件中，qcvideo组件播放了视频，点击视频区域无法调起暂停的操作面板，安卓出现这种情况，iOS不会，是因为事件冲突了吗

**Comment by theniceangel** [comment]
[按照这个配置项试试](https://better-scroll.github.io/docs/zh-CN/guide/base-scroll-options.html#preventdefaultexception)

**Comment by JElaine** [comment]
解决了，感谢
