### ISSUE TITLE
scroll组件上下滚动在iOS上偶尔会出现部分白屏

### ISSUE THREAD

**Issue by JElaine** [cube-ui/question-answer#91]
在iOS上下滚动，偶尔会出现半截白屏，再滚动一下又会恢复正常，我是在一个scroll中嵌套了一个scroll

**Comment by G-c-chen** [comment]
你是不是加了 -webkit-overflow-scrolling:touch这个属性，如果是，那应该是这个导致的，应该不是嵌套导致的

**Comment by Monster-hw** [comment]
> 你是不是加了 -webkit-overflow-scrolling:touch这个属性，如果是，那应该是这个导致的，应该不是嵌套导致的

我也出现了这种问题，但并没有设置 -webkit-overflow-scrolling:touch这个属性

**Comment by dolymood** [comment]
去官方仓库提issue，按照规范以及这种case最好有视频

**Comment by JElaine** [comment]
哪个官方仓库

**Comment by dolymood** [comment]
didi/cube-ui
