### ISSUE TITLE
下拉之后松开。执行上拉刷新的方法，执行完成之后，beforePullDown的为false,isPullingDown的值为true，这时候再次下拉，发现不会触发下拉刷新的方法并且也不能触发上拉加载的方法，显示下拉动画的地方一直显示loading,loading不会消失，在下拉刷新的方法的最后手动forceUpdate，还是不能解决这个问题，用了自定义的动画，还是不能解决这个问题

### ISSUE THREAD

**Issue by zhengyn0001** [cube-ui/question-answer#97]
![image](https://user-images.githubusercontent.com/51322469/64413928-0dca3080-d0c5-11e9-8075-3e7bd6886de2.png)
![image](https://user-images.githubusercontent.com/51322469/64413974-21759700-d0c5-11e9-9e55-b58719cb1875.png)
![image](https://user-images.githubusercontent.com/51322469/64414037-3a7e4800-d0c5-11e9-89b8-3044e0b7225a.png)

**Comment by dolymood** [comment]
这个升级到最新版应该解决了这个问题了

**Comment by zhengyn0001** [comment]
我已经升级到1.12.30的这个版本了，这个版本不是最新的版本吗

**Comment by dolymood** [comment]
那你就去官方仓库 提复现demo，以及你这种case感觉应该需要个视频 可能会好点
